learing classification algorithm

In [145]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')

In [146]:
df = sns.load_dataset('titanic')

In [147]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [148]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')

In [149]:
df.dtypes

survived          int64
pclass            int64
sex                 str
age             float64
sibsp             int64
parch             int64
fare            float64
embarked            str
class          category
who                 str
adult_male         bool
deck           category
embark_town         str
alive               str
alone              bool
dtype: object

In [150]:
df.shape

(891, 15)

In [151]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [152]:
df.drop(['deck','embark_town', 'class', 'who', 'adult_male','alive'],axis = 1,inplace=True)

In [153]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    str
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    str
 8   alone     891 non-null    bool
dtypes: bool(1), float64(2), int64(4), str(2)
memory usage: 56.7 KB

In [154]:
df["age"].fillna(df["age"].mean(),inplace=True)

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: age, Length: 891, dtype: float64

In [155]:
df.dropna(subset=["embarked"],inplace=True)

In [156]:
df.info()

<class 'pandas.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  889 non-null    int64
 1   pclass    889 non-null    int64
 2   sex       889 non-null    str
 3   age       712 non-null    float64
 4   sibsp     889 non-null    int64
 5   parch     889 non-null    int64
 6   fare      889 non-null    float64
 7   embarked  889 non-null    str
 8   alone     889 non-null    bool
dtypes: bool(1), float64(2), int64(4), str(2)
memory usage: 63.4 KB

In [157]:
df["age"] = df["age"].fillna(df["age"].mean())

In [158]:
df.info()

<class 'pandas.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  889 non-null    int64
 1   pclass    889 non-null    int64
 2   sex       889 non-null    str
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64
 5   parch     889 non-null    int64
 6   fare      889 non-null    float64
 7   embarked  889 non-null    str
 8   alone     889 non-null    bool
dtypes: bool(1), float64(2), int64(4), str(2)
memory usage: 63.4 KB

In [159]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['sex'] = le.fit_transform(df['sex'])
df['embarked'] = le.fit_transform(df['embarked'])
df['alone'] = le.fit_transform(df['alone'])

In [160]:
df.head()

   survived  pclass  sex   age  sibsp  parch     fare  embarked  alone
0         0       3    1  22.0      1      0   7.2500         2      0
1         1       1    0  38.0      1      0  71.2833         0      0
2         1       3    0  26.0      0      0   7.9250         2      1
3         1       1    0  35.0      1      0  53.1000         2      0
4         0       3    1  35.0      0      0   8.0500         2      1

In [161]:
x= df.drop('survived',axis=1)
y= df['survived']

In [162]:
from sklearn.model_selection import train_test_split

In [163]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [164]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [165]:
model.fit(x_train,y_train)

LogisticRegression()

In [166]:
y_pred = model.predict(x_test)

In [167]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test,y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.8033707865168539

In [168]:
from sklearn.metrics import precision_score, recall_score, f1_score

print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))

Precision: 0.7361111111111112
Recall: 0.7681159420289855
F1 Score: 0.75177304964539

logistic regration model evaluation

In [169]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.83      0.84       109
           1       0.74      0.77      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.80      0.79       178
weighted avg       0.81      0.80      0.80       178

In [170]:
x_train

     pclass  sex        age  sibsp  parch      fare  embarked  alone
708       1    0  22.000000      0      0  151.5500         2      1
240       3    0  29.642093      1      0   14.4542         0      0
382       3    1  32.000000      0      0    7.9250         2      1
792       3    0  29.642093      8      2   69.5500         2      0
683       3    1  14.000000      5      2   46.9000         2      0
..      ...  ...        ...    ...    ...       ...       ...    ...
107       3    1  29.642093      0      0    7.7750         2      1
271       3    1  25.000000      0      0    0.0000         2      1
862       1    0  48.000000      0      0   25.9292         2      1
436       3    0  21.000000      2      2   34.3750         2      0
103       3    1  33.000000      0      0    8.6542         2      1

[711 rows x 8 columns]

In [171]:
x_test

     pclass  sex   age  sibsp  parch      fare  embarked  alone
281       3    1  28.0      0      0    7.8542         2      1
435       1    0  14.0      1      2  120.0000         2      0
39        3    0  14.0      1      0   11.2417         0      0
418       2    1  30.0      0      0   13.0000         2      1
585       1    0  18.0      0      2   79.6500         2      0
..      ...  ...   ...    ...    ...       ...       ...    ...
433       3    1  17.0      0      0    7.1250         2      1
807       3    0  18.0      0      0    7.7750         2      1
25        3    0  38.0      1      5   31.3875         2      0
85        3    0  33.0      3      0   15.8500         2      0
10        3    0   4.0      1      1   16.7000         2      0

[178 rows x 8 columns]

KNN k-nerest neighbors

In [172]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)

x_test_scaled = scaler.transform(x_test)

In [173]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=5)

In [174]:
model.fit(x_train_scaled,y_train)

KNeighborsClassifier()

In [175]:
y_pred_knn = model.predict(x_test_scaled )

In [176]:
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [177]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_knn))

              precision    recall  f1-score   support

           0       0.84      0.83      0.83       109
           1       0.73      0.75      0.74        69

    accuracy                           0.80       178
   macro avg       0.79      0.79      0.79       178
weighted avg       0.80      0.80      0.80       178

naive byes

In [178]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()

model.fit(x_train, y_train)

GaussianNB()

In [179]:
y_pred_nb = model.predict(x_test)

In [180]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_nb))

              precision    recall  f1-score   support

           0       0.85      0.77      0.81       109
           1       0.68      0.78      0.73        69

    accuracy                           0.78       178
   macro avg       0.77      0.78      0.77       178
weighted avg       0.78      0.78      0.78       178

Decision tree algorithm

In [181]:
from sklearn.tree import DecisionTreeClassifier

In [182]:
model = DecisionTreeClassifier(random_state=42)

In [183]:
x_train

     pclass  sex        age  sibsp  parch      fare  embarked  alone
708       1    0  22.000000      0      0  151.5500         2      1
240       3    0  29.642093      1      0   14.4542         0      0
382       3    1  32.000000      0      0    7.9250         2      1
792       3    0  29.642093      8      2   69.5500         2      0
683       3    1  14.000000      5      2   46.9000         2      0
..      ...  ...        ...    ...    ...       ...       ...    ...
107       3    1  29.642093      0      0    7.7750         2      1
271       3    1  25.000000      0      0    0.0000         2      1
862       1    0  48.000000      0      0   25.9292         2      1
436       3    0  21.000000      2      2   34.3750         2      0
103       3    1  33.000000      0      0    8.6542         2      1

[711 rows x 8 columns]

In [184]:
y_train

708    1
240    0
382    0
792    0
683    0
      ..
107    1
271    1
862    1
436    0
103    0
Name: survived, Length: 711, dtype: int64

In [185]:
model.fit(x_train_scaled,y_train)

DecisionTreeClassifier(random_state=42)

In [186]:
y_pred_dt = model.predict(x_test_scaled)

In [187]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred_dt))

              precision    recall  f1-score   support

           0       0.83      0.73      0.78       109
           1       0.65      0.77      0.70        69

    accuracy                           0.75       178
   macro avg       0.74      0.75      0.74       178
weighted avg       0.76      0.75      0.75       178

SVM == support vector machine

In [188]:
from sklearn.svm import SVC

In [189]:
model_svc = SVC()

In [190]:
model_svc.fit(x_train_scaled,y_train)

SVC()

In [191]:
y_pred_svm = model_svc.predict(x_test_scaled)

In [192]:
print(classification_report(y_test, y_pred_svm))

              precision    recall  f1-score   support

           0       0.86      0.83      0.85       109
           1       0.75      0.78      0.77        69

    accuracy                           0.81       178
   macro avg       0.80      0.81      0.81       178
weighted avg       0.82      0.81      0.82       178

CROSS VALIDATION

In [193]:
df

     survived  pclass  sex        age  sibsp  parch     fare  embarked  alone
0           0       3    1  22.000000      1      0   7.2500         2      0
1           1       1    0  38.000000      1      0  71.2833         0      0
2           1       3    0  26.000000      0      0   7.9250         2      1
3           1       1    0  35.000000      1      0  53.1000         2      0
4           0       3    1  35.000000      0      0   8.0500         2      1
..        ...     ...  ...        ...    ...    ...      ...       ...    ...
886         0       2    1  27.000000      0      0  13.0000         2      1
887         1       1    0  19.000000      0      0  30.0000         2      1
888         0       3    0  29.642093      1      2  23.4500         2      0
889         1       1    1  26.000000      0      0  30.0000         0      1
890         0       3    1  32.000000      0      0   7.7500         1      1

[889 rows x 9 columns]

In [194]:
X = df.drop('survived',axis=1)
y = df['survived']

In [195]:
from sklearn.model_selection  import cross_val_score

In [196]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [197]:
x_scaled = scaler.fit_transform(X)

In [198]:
scors = cross_val_score(model_svc,x_scaled,y,cv=5,scoring='accuracy')

In [199]:
print(scors)

[0.83146067 0.82022472 0.81460674 0.80898876 0.86440678]

In [200]:
print(scors.mean())

0.8279375357074844

Hyperparameter Tuning

In [201]:
from sklearn.model_selection import GridSearchCV

params = {
    "n_neighbors": [3, 5, 7, 9]
}

grid = GridSearchCV(
    KNeighborsClassifier(),
    params,
    cv=5
)

grid.fit(x_train_scaled, y_train)

print(grid.best_params_)
print(grid.best_score_)

{'n_neighbors': 3}
0.8213631438983551

Random search cv

In [202]:
from sklearn.model_selection import RandomizedSearchCV

In [203]:
params = {
    "C": [0.1, 1, 10, 100],
    "kernel": ["linear", "rbf", "poly"],
    "gamma": ["scale", "auto"]
}

In [204]:
random_search = RandomizedSearchCV(
    model_svc,
    param_distributions=params,
    n_iter=10,
    cv=5,
    scoring="accuracy",
    random_state=42
)

random_search.fit(x_train_scaled, y_train)

print(random_search.best_params_)
print(random_search.best_score_)

{'kernel': 'rbf', 'gamma': 'auto', 'C': 10}
0.8213631438983553

Esemble Learning =============

Stacking -----------

In [205]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import StackingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model  import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report
import seaborn as sns

In [206]:
df = sns.load_dataset('iris')

In [207]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [208]:
X = df.drop('species',axis=1)
y = df['species']

In [209]:
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.2, random_state=42)

In [210]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [211]:
base_lerners =[
    ('dt',DecisionTreeClassifier(random_state=42)),
    ('svc',SVC(probability=True,kernel='rbf',random_state=42)),
    ('lr',LogisticRegression(max_iter=1000))
]

In [212]:
meta_learner = LogisticRegression(max_iter=1000)

In [213]:
stacking_clf = StackingClassifier(
    estimators=base_lerners,
    final_estimator=meta_learner,
    cv=5
)

In [214]:
stacking_clf.fit(X_train_scaled,y_train)

StackingClassifier(cv=5,
                   estimators=[('dt', DecisionTreeClassifier(random_state=42)),
                               ('svc', SVC(probability=True, random_state=42)),
                               ('lr', LogisticRegression(max_iter=1000))],
                   final_estimator=LogisticRegression(max_iter=1000))

In [215]:
y_pred = stacking_clf.predict(X_test_scaled)

In [216]:
print(accuracy_score(y_test,y_pred))

1.0

Bagging====================

In [220]:
from sklearn.ensemble import BaggingClassifier

base_model = BaggingClassifier(random_state=42)

In [221]:
bagging_clf = BaggingClassifier(
    estimator=base_model,
    n_estimators=10,
    random_state=42
)

In [222]:
bagging_clf.fit(X_train,y_train)

BaggingClassifier(estimator=BaggingClassifier(random_state=42), random_state=42)

In [223]:
y_pred = bagging_clf.predict(X_test)

In [224]:
print(accuracy_score(y_test,y_pred))

1.0

In [226]:
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    max_depth=None
)

In [227]:
rf_model.fit(X_train,y_train)

RandomForestClassifier(random_state=42)

In [228]:
y_pred = rf_model.predict(X_test)

In [229]:
print(accuracy_score(y_test,y_pred))

1.0